### ISSUE TITLE
`CelltypeSpecificPeaks` errors

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/CHAS#1]
When following vignette, the following errors can occur at this step:

```R
celltype_specific_peaks <- CelltypeSpecificPeaks(EntorhinalCortex_AD_H3K27ac_peaks, celltypePeaks, 0.5) 
```

## Error 1.

```
Error in IRanges(start = bulkPeaks[, 2], end = bulkPeaks[, 3]) : 
  could not find function "IRanges" 
```
### Solution

In your code, call `IRanges::IRanges` instead of `IRanges` by itself.  Or (less desirably) export all functions from `IRanges` upon loading `CHAS`.

## Error 2. 

```
Error in Reduce(full_join, annotBulkPeaksList) : 
  object 'full_join' not found 
```

### Solution

Assuming `full_join` is from some other package (perhaps `sparklyr`?), call it explicitly with `some_pkg::full_join`.
Also, whatever package this is, make sure to add it your Imports within your DESCRIPTION file.

**Comment by KittyMurphy** [comment]
Code now calls IRanges::IRanges and dplyr::full_join
