### ISSUE TITLE
`plot_celltype_props` error

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/CHAS#3]
When running the following step of the vignette:

```R
plot_celltype_props(celltype_specific_peaks, exampleData=TRUE)
```

## Error 1.  

```
Error in ggplot(PropTable, aes(x = Source, y = Freq, fill = Var1)) : 
  could not find function "ggplot"
```

### Solution

Add `ggplot2` to Imports sections of description file, and add the following to the Roxygen notes of your `plot_celltype_props` function:

```
#' @import ggplot2
```

**Comment by KittyMurphy** [comment]
Added ggplot2 to imports section of description file and @import ggplot2 to plot_celltype_props
