### ISSUE TITLE
`plot_celltype_scores` error

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/CHAS#4]
When running the following in the vignette:

```R
plot_celltype_scores(celltype_scores, AD_pheno)
```

## Error 1.

```
Error: object 'AD_pheno' not found
```
### Solution 

Either create `AD_pheno` in the vignette, or load it as a built-in dataset.

**Comment by bschilder** [comment]
Also make sure to add `ggplot2` as an import, same as here: #3

**Comment by KittyMurphy** [comment]
Added AD_pheno as a built-in dataset
Added ggplot2 to imports section of description file and @import ggplot2 to plot_celltype_scores
